name: Run Script on File Change

on:
  push:
    paths:
      - 'matrix/drivers_matrix.MD5SUM'
  pull_request:
    paths:
      - 'matrix/drivers_matrix.MD5SUM' 

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run script
        working-directory: matrix
        run: |
          bash create_matrix.sh
          bash update_dockerfile.sh

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update Dockerfile for new release via GitHub Action"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
