name: Check for data changes
on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  check_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Read contents of MD5SUM in repository
        id: read-repo-file
        run: echo "md5_repo=$(cat drivers_matrix.MD5SUM)" >> "$GITHUB_ENV"
        working-directory: matrix
      - name: Run matrix
        id: run-matrix
        working-directory: matrix
        run: |
          bash create_matrix.sh
          bash update_dockerfile.sh
          echo "md5_live=$(cat drivers_matrix.MD5SUM)" >> "$GITHUB_ENV"
      - name: Show differences
        id: show-diffs
        run: |
          echo "MD5 REPO:"
          printf '%s\n' "$md5_repo" 
          echo "MD5 LIVE:"
          printf '%s\n' "$md5_live" 
      - name: Commit changes
        if: steps.set-var.outputs.md5_results == 'different'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "actions-user"
          git add .
          git commit -m "[NEW_BUILD] New release via GitHub Action"
      - name: Push changes
        if: steps.set-var.outputs.md5_results == 'different'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

